apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  # 1 copy of nginx should exists at all times
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
