apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  # 1 copy of nginx shoulds exists at all times
  replicas: 1
  selector:
    matchLabels:
      tier: frontends
  template:
    metadata:
      labels:
        tier: frontends
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
